# Generated by Django 3.0.3 on 2020-03-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.CharField(blank=True, default='', max_length=30, unique=True)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
